import { useState } from 'react'
import type { InteractiveLessonProps } from '../../../engine/types'
import { evaluateBrief, type BriefChoices } from '../../../simulation/brief'
import { BriefBlocks } from '../../../ui/BriefBlocks'
import { Feedback } from '../../../ui/Feedback'
import { ScoreBreakdown } from '../../../ui/ScoreBreakdown'
import { SimulationPanel } from '../../../ui/SimulationPanel'
import { decisionMemoBrief } from '../data/brief'

export function MemoBuilder({ onComplete, completed }: InteractiveLessonProps) {
  const [choices, setChoices] = useState<BriefChoices>({})
  const r = evaluateBrief(decisionMemoBrief, choices)
  const ready = r.score >= 80

  return (
    <div className="space-y-6">
      <p className="ink-2">
        The Meridian engagement runs out in December and your engagement partner wants a one-page memo.
        Build the request block by block. The preview on the right shows the kind of memo a request
        like yours tends to produce. Reach <strong className="ink-1">80</strong> to continue.
      </p>

      <SimulationPanel
        title="Memo Builder"
        aside={
          <div className="space-y-3 md:sticky md:top-20">
            <div className="card p-3" aria-live="polite">
              <p className="text-xs font-semibold uppercase tracking-wide ink-3">Likely memo</p>
              <ol className="mt-2 space-y-1 text-sm" key={r.outline[0]}>
                {r.outline.map((line) => (
                  <li key={line} className="animate-rise ink-1">
                    {line}
                  </li>
                ))}
              </ol>
              <p className="mt-2 text-xs ink-3">Illustrative example, not generated by a model.</p>
            </div>
          </div>
        }
      >
        <div className="space-y-4">
          <BriefBlocks spec={decisionMemoBrief} choices={choices} onChange={setChoices} />
          <div className="rounded-xl surface-2 p-3 text-sm">
            <p className="text-xs font-semibold uppercase tracking-wide ink-3">Your message to Claude</p>
            <p className="mt-1 ink-1">{r.text || '…'}</p>
          </div>
        </div>
      </SimulationPanel>

      <ScoreBreakdown total={r.score} dimensions={r.breakdown} label="Brief score" />
      <Feedback items={r.feedback.filter((f) => f.tone !== 'positive').slice(0, 3)} heading="What would make it better" />

      <div className="flex justify-end">
        <button type="button" className="btn btn-primary" onClick={onComplete} disabled={!ready && !completed}>
          {completed ? 'Next' : ready ? 'Continue' : 'Reach a score of 80 to continue'}
        </button>
      </div>
    </div>
  )
}
